spring.application.name=text-to-speech-backend

server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/tts_database
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# CORS
spring.web.cors.allowed-origins=http://localhost:5173